# Generated by Django 5.2.8 on 2025-12-01 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localshop', '0002_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_record', to='localshop.product')),
            ],
        ),
    ]
