# Generated by Django 5.2.8 on 2025-12-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localshop', '0003_deletedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_record', to='localshop.product'),
        ),
    ]
