# Generated by Django 5.2.8 on 2025-12-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localshop', '0004_alter_deletedproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
