# Generated by Django 5.2.8 on 2025-12-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localshop', '0005_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notified_about_discount',
            field=models.BooleanField(default=False),
        ),
    ]
